/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import AppPackage.AnimationClass;
import Controlador.Controlador;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Ventana principal de usuario
 * @author Equipo 3(Raúl Melgosa, Oier Velar, Alaitz Candela)
 */
public class VpartidosUsu extends javax.swing.JFrame {
private int xMouse,yMouse;
private boolean menuAbierto=false;
private boolean listaDesplegableAlta;
private boolean listaDesplegableBaja;
private boolean listaDesplegableModificaciones;
private boolean listaDesplegableConsulta;
AnimationClass animacion = new AnimationClass();
private ArrayList<String> listaPartidos = new ArrayList();
private String jornada;

    /**
     * Creates new form VprincipalUsu
     */
    public VpartidosUsu() {
        initComponents();
        bMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png")));
        setLocationRelativeTo(null);
        barraDrag.setBackground(new java.awt.Color(0,0,0,0));
        menu.setBackground(new Color(45,45,45,200));
        this.menuAbierto=false;
        this.listaDesplegableAlta=false;
        this.listaDesplegableBaja=false;
        this.listaDesplegableModificaciones=false;
        this.listaDesplegableConsulta=false;
        Controlador.PedirUltimaJornada(cbPartido);
        for(int x=0;x<listaPartidos.size();x++){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCerrar = new javax.swing.JLabel();
        bMinimizar = new javax.swing.JLabel();
        barraDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bMenu = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        bResultadosJornada = new javax.swing.JLabel();
        bClasificacionGeneral = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        gifAbajo = new javax.swing.JLabel();
        GIFarriba = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelLocal = new javax.swing.JLabel();
        tfLocal = new javax.swing.JTextField();
        labelHora = new javax.swing.JLabel();
        tfVisitante = new javax.swing.JTextField();
        labelVisitante = new javax.swing.JLabel();
        labelJornada = new javax.swing.JLabel();
        cbPartido = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 63, 65));
        setMinimumSize(new java.awt.Dimension(1500, 750));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCerrar.setBackground(new java.awt.Color(45, 45, 45));
        bCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-white.png"))); // NOI18N
        bCerrar.setOpaque(true);
        bCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCerrarMouseExited(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 40, 30));

        bMinimizar.setBackground(new java.awt.Color(45, 45, 45));
        bMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png"))); // NOI18N
        bMinimizar.setOpaque(true);
        bMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMinimizarMouseExited(evt);
            }
        });
        getContentPane().add(bMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 0, 40, -1));

        barraDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraDragMouseDragged(evt);
            }
        });
        barraDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraDragMousePressed(evt);
            }
        });
        getContentPane().add(barraDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        bMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMenuMouseClicked(evt);
            }
        });
        jPanel1.add(bMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 50));

        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 60, 40, 40));

        bResultadosJornada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bResultadosJornada.setForeground(new java.awt.Color(255, 255, 255));
        bResultadosJornada.setText("     Resultados Jornada");
        bResultadosJornada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bResultadosJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 120, 300, 30));

        bClasificacionGeneral.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bClasificacionGeneral.setForeground(new java.awt.Color(255, 255, 255));
        bClasificacionGeneral.setText("     Clasificación general");
        bClasificacionGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bClasificacionGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bClasificacionGeneralMouseClicked(evt);
            }
        });
        jPanel1.add(bClasificacionGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 160, 300, 30));

        menu.setBackground(new java.awt.Color(120, 120, 120));
        menu.setOpaque(true);
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 50, 300, 700));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO-small.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        gifAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte2.gif"))); // NOI18N
        jPanel1.add(gifAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 500, 500));

        GIFarriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte1.gif"))); // NOI18N
        jPanel1.add(GIFarriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 500, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 750));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLocal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLocal.setForeground(new java.awt.Color(255, 255, 255));
        labelLocal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelLocal.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel2.add(labelLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 250, 40));

        tfLocal.setEditable(false);
        tfLocal.setBackground(new java.awt.Color(45, 45, 45));
        tfLocal.setForeground(new java.awt.Color(255, 255, 255));
        tfLocal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfLocal.setBorder(null);
        tfLocal.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(tfLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 40));

        labelHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));
        labelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 80, 40));

        tfVisitante.setEditable(false);
        tfVisitante.setBackground(new java.awt.Color(45, 45, 45));
        tfVisitante.setForeground(new java.awt.Color(255, 255, 255));
        tfVisitante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfVisitante.setBorder(null);
        tfVisitante.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(tfVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 110, 40));

        labelVisitante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVisitante.setForeground(new java.awt.Color(255, 255, 255));
        labelVisitante.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel2.add(labelVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 250, 40));

        labelJornada.setBackground(new java.awt.Color(255, 255, 255));
        labelJornada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelJornada.setForeground(new java.awt.Color(255, 255, 255));
        labelJornada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJornada.setText("ÚLTIMA JORNADA");
        jPanel2.add(labelJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 60));

        cbPartido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona Partido--" }));
        cbPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPartidoActionPerformed(evt);
            }
        });
        jPanel2.add(cbPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 230, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 80, 1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 280, 80, 1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPartidoActionPerformed
        
        try
        {
            if(!cbPartido.getSelectedItem().toString().equals("--Selecciona Partido--"))
            {
                int idPartido;
                idPartido=Integer.parseInt(cbPartido.getSelectedItem().toString());
                ArrayList<String> datos=Controlador.getDatosPartido(idPartido);
                labelLocal.setText(datos.get(0));
                tfLocal.setText(datos.get(1));
                labelHora.setText(datos.get(2));
                tfVisitante.setText(datos.get(4));
                labelVisitante.setText(datos.get(3));
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getClass());
            System.out.println(e.getCause());
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado");
        }
        
    }//GEN-LAST:event_cbPartidoActionPerformed

    private void bMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenuMouseClicked
        if(menuAbierto){
            menuAbierto=false;
            animacion.jLabelXLeft(menu.getX(), menu.getX()-300, 3, 5, menu);animacion.jLabelXLeft(bResultadosJornada.getX(),bResultadosJornada.getX()-300, 3, 5, bResultadosJornada);
            animacion.jLabelXLeft(bClasificacionGeneral.getX(),bClasificacionGeneral.getX()-300, 3, 5, bClasificacionGeneral);
            animacion.jLabelXLeft(bLogout.getX(), bLogout.getX()-300, 3, 5, bLogout);
        }
        else{

            bResultadosJornada.setLocation(-300, 110);
            bClasificacionGeneral.setLocation(-300, 150);
            menuAbierto=true;
            animacion.jLabelXRight(menu.getX(), menu.getX()+300, 3, 5, menu);

            animacion.jLabelXRight(bResultadosJornada.getX(),bResultadosJornada.getX()+300, 3, 5, bResultadosJornada);
            animacion.jLabelXRight(bClasificacionGeneral.getX(),bClasificacionGeneral.getX()+300, 3, 5, bClasificacionGeneral);
            animacion.jLabelXRight(bLogout.getX(), bLogout.getX()+300, 3, 5, bLogout);
        }
    }//GEN-LAST:event_bMenuMouseClicked

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        Controlador.VentanaLogin(this);
    }//GEN-LAST:event_bLogoutMouseClicked

    private void barraDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraDragMouseDragged

    private void barraDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraDragMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barraDragMousePressed

    private void bCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseClicked
        Controlador.salir();
    }//GEN-LAST:event_bCerrarMouseClicked

    private void bCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseEntered
        bCerrar.setBackground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_bCerrarMouseEntered

    private void bCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseExited
        bCerrar.setBackground(new java.awt.Color(45, 45, 45));
    }//GEN-LAST:event_bCerrarMouseExited

    private void bMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinimizarMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_bMinimizarMouseClicked

    private void bMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinimizarMouseEntered
        bMinimizar.setBackground(new Color(100,100,100));
    }//GEN-LAST:event_bMinimizarMouseEntered

    private void bMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinimizarMouseExited
        bMinimizar.setBackground(new java.awt.Color(45, 45, 45));
    }//GEN-LAST:event_bMinimizarMouseExited

    private void bClasificacionGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bClasificacionGeneralMouseClicked
        Controlador.VentanaClasificacion(this);
    }//GEN-LAST:event_bClasificacionGeneralMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VpartidosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VpartidosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VpartidosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VpartidosUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VpartidosUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GIFarriba;
    private javax.swing.JLabel bCerrar;
    private javax.swing.JLabel bClasificacionGeneral;
    private javax.swing.JLabel bLogout;
    private javax.swing.JLabel bMenu;
    private javax.swing.JLabel bMinimizar;
    private javax.swing.JLabel bResultadosJornada;
    private javax.swing.JLabel barraDrag;
    private javax.swing.JComboBox<String> cbPartido;
    private javax.swing.JLabel gifAbajo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelJornada;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JLabel labelVisitante;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField tfLocal;
    private javax.swing.JTextField tfVisitante;
    // End of variables declaration//GEN-END:variables
}
