/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Jugadores;

import Views.Equipos.*;

/**
 *
 * @author Alaitzutzu
 */
public class AltaJugador extends javax.swing.JFrame {

    /**
     * Creates new form AltaEquipo
     */
    public AltaJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        barraDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GifArriba = new javax.swing.JLabel();
        GifAbajo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfIdEquipo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Baceptar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        tfApellidos = new javax.swing.JTextField();
        tfNickname = new javax.swing.JTextField();
        tfDorsal = new javax.swing.JTextField();
        tfSueldo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        bJungla = new javax.swing.JLabel();
        bMid = new javax.swing.JLabel();
        bAdc = new javax.swing.JLabel();
        bSuplente = new javax.swing.JLabel();
        bTop = new javax.swing.JLabel();
        bSupport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 750));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png"))); // NOI18N
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 0, 30, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-white.png"))); // NOI18N
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 40, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(barraDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 1500, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GifArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte1.gif"))); // NOI18N
        jPanel1.add(GifArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, -1));

        GifAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte2.gif"))); // NOI18N
        jPanel1.add(GifAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 750));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alta Jugadores");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DNI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        tfDni.setEditable(false);
        tfDni.setBackground(new java.awt.Color(45, 45, 45));
        tfDni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDni.setForeground(new java.awt.Color(255, 255, 255));
        tfDni.setText("Dni");
        tfDni.setToolTipText("Introduce el ID del equipo");
        tfDni.setBorder(null);
        jPanel2.add(tfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 260, -1));

        tfNombre.setEditable(false);
        tfNombre.setBackground(new java.awt.Color(45, 45, 45));
        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfNombre.setText("Nombre");
        tfNombre.setToolTipText("Introduce el nombre del equipo");
        tfNombre.setBorder(null);
        jPanel2.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 250, -1));

        tfIdEquipo.setBackground(new java.awt.Color(45, 45, 45));
        tfIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIdEquipo.setForeground(new java.awt.Color(255, 255, 255));
        tfIdEquipo.setText("ID Equipo");
        tfIdEquipo.setToolTipText("Introduce el id del jefe");
        tfIdEquipo.setBorder(null);
        tfIdEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdEquipoActionPerformed(evt);
            }
        });
        jPanel2.add(tfIdEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 250, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 290, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 290, 10));
        jPanel2.add(Baceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nickname");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rol");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dorsal");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sueldo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Equipo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 290, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 290, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 290, 10));

        tfApellidos.setBackground(new java.awt.Color(45, 45, 45));
        tfApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfApellidos.setForeground(new java.awt.Color(255, 255, 255));
        tfApellidos.setText("Apellidos");
        tfApellidos.setToolTipText("Introduce el id del jefe");
        tfApellidos.setBorder(null);
        tfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidosActionPerformed(evt);
            }
        });
        jPanel2.add(tfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 250, -1));

        tfNickname.setBackground(new java.awt.Color(45, 45, 45));
        tfNickname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNickname.setForeground(new java.awt.Color(255, 255, 255));
        tfNickname.setText("Nickname");
        tfNickname.setToolTipText("Introduce el id del jefe");
        tfNickname.setBorder(null);
        tfNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNicknameActionPerformed(evt);
            }
        });
        jPanel2.add(tfNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 250, -1));

        tfDorsal.setBackground(new java.awt.Color(45, 45, 45));
        tfDorsal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDorsal.setForeground(new java.awt.Color(255, 255, 255));
        tfDorsal.setText("Dorsal");
        tfDorsal.setToolTipText("Introduce el id del jefe");
        tfDorsal.setBorder(null);
        tfDorsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDorsalActionPerformed(evt);
            }
        });
        jPanel2.add(tfDorsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 250, -1));

        tfSueldo.setBackground(new java.awt.Color(45, 45, 45));
        tfSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSueldo.setForeground(new java.awt.Color(255, 255, 255));
        tfSueldo.setText("Sueldo");
        tfSueldo.setToolTipText("Introduce el id del jefe");
        tfSueldo.setBorder(null);
        tfSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSueldoActionPerformed(evt);
            }
        });
        jPanel2.add(tfSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 250, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 290, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 290, 10));

        bJungla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png"))); // NOI18N
        bJungla.setToolTipText("Jungla");
        bJungla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJunglaMouseClicked(evt);
            }
        });
        jPanel2.add(bJungla, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 40, 50));

        bMid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png"))); // NOI18N
        bMid.setToolTipText("Mid");
        bMid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMidMouseClicked(evt);
            }
        });
        jPanel2.add(bMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 40, 50));

        bAdc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png"))); // NOI18N
        bAdc.setToolTipText("Adc");
        bAdc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAdcMouseClicked(evt);
            }
        });
        jPanel2.add(bAdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 40, 50));

        bSuplente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png"))); // NOI18N
        bSuplente.setToolTipText("Suplente");
        bSuplente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSuplenteMouseClicked(evt);
            }
        });
        jPanel2.add(bSuplente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 40, 50));

        bTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png"))); // NOI18N
        bTop.setToolTipText("Top");
        bTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTopMouseClicked(evt);
            }
        });
        jPanel2.add(bTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 40, 50));

        bSupport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png"))); // NOI18N
        bSupport.setToolTipText("Support");
        bSupport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSupportMouseClicked(evt);
            }
        });
        jPanel2.add(bSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 40, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdEquipoActionPerformed

    private void tfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidosActionPerformed

    private void tfNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNicknameActionPerformed

    private void tfDorsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDorsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDorsalActionPerformed

    private void tfSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSueldoActionPerformed

    private void bJunglaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJunglaMouseClicked
       bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jungle_icon.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png"))); 
    }//GEN-LAST:event_bJunglaMouseClicked

    private void bTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTopMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Top_icon.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
    }//GEN-LAST:event_bTopMouseClicked

    private void bMidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMidMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Middle_icon.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
    }//GEN-LAST:event_bMidMouseClicked

    private void bAdcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAdcMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bottom_icon.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
    }//GEN-LAST:event_bAdcMouseClicked

    private void bSupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSupportMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Support_icon.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
    }//GEN-LAST:event_bSupportMouseClicked

    private void bSuplenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSuplenteMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill.png")));
    }//GEN-LAST:event_bSuplenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baceptar;
    private javax.swing.JLabel GifAbajo;
    private javax.swing.JLabel GifArriba;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel bAdc;
    private javax.swing.JLabel bJungla;
    private javax.swing.JLabel bMid;
    private javax.swing.JLabel bSuplente;
    private javax.swing.JLabel bSupport;
    private javax.swing.JLabel bTop;
    private javax.swing.JLabel barraDrag;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfDorsal;
    private javax.swing.JTextField tfIdEquipo;
    private javax.swing.JTextField tfNickname;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSueldo;
    // End of variables declaration//GEN-END:variables
}
