/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Jugadores;

import Controlador.Controlador;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author Alaitzutzu
 */
public class ModifJugador extends javax.swing.JFrame {

    /**
     * Creates new form AltaEquipo
     */
private char modo;
private String rol;
private String nombreEquipo;    
    public ModifJugador() {
        initComponents();
        setLocationRelativeTo(null);
        Controlador.LLenarComboBoxEquipo(CBequipos);
        Controlador.LlenarComboBoxJugador(CBjugadores);
        jPanel2.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        barraDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GifArriba = new javax.swing.JLabel();
        GifAbajo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        barraDni = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfDorsal = new javax.swing.JTextField();
        tfSueldo = new javax.swing.JTextField();
        barraDorsal = new javax.swing.JSeparator();
        barraSueldo = new javax.swing.JSeparator();
        bJungla = new javax.swing.JLabel();
        bMid = new javax.swing.JLabel();
        bAdc = new javax.swing.JLabel();
        bSuplente = new javax.swing.JLabel();
        bTop = new javax.swing.JLabel();
        bSupport = new javax.swing.JLabel();
        CBequipos = new javax.swing.JComboBox<>();
        Baceptar = new javax.swing.JLabel();
        CBjugadores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 750));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png"))); // NOI18N
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 0, 30, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-white.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 40, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(barraDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 1500, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GifArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte1.gif"))); // NOI18N
        jPanel1.add(GifArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, -1));

        GifAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte2.gif"))); // NOI18N
        jPanel1.add(GifAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 750));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificacion Jugadores");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dni-white.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        tfDni.setEditable(false);
        tfDni.setBackground(new java.awt.Color(45, 45, 45));
        tfDni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDni.setForeground(new java.awt.Color(255, 255, 255));
        tfDni.setText("Dni");
        tfDni.setToolTipText("Introduce el Dni del jugador");
        tfDni.setBorder(null);
        tfDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDniFocusLost(evt);
            }
        });
        tfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDniKeyReleased(evt);
            }
        });
        jPanel2.add(tfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 270, 30));

        barraDni.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(barraDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 290, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rol");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dorsal-white.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/euro-white.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo-white.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 30, 30));

        tfDorsal.setBackground(new java.awt.Color(45, 45, 45));
        tfDorsal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDorsal.setForeground(new java.awt.Color(255, 255, 255));
        tfDorsal.setText("Dorsal");
        tfDorsal.setToolTipText("Introduce el dorsal del jugador");
        tfDorsal.setBorder(null);
        tfDorsal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDorsalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDorsalFocusLost(evt);
            }
        });
        tfDorsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDorsalKeyReleased(evt);
            }
        });
        jPanel2.add(tfDorsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 280, 30));

        tfSueldo.setBackground(new java.awt.Color(45, 45, 45));
        tfSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSueldo.setForeground(new java.awt.Color(255, 255, 255));
        tfSueldo.setText("Sueldo");
        tfSueldo.setToolTipText("Introduce el sueldo del jugador");
        tfSueldo.setBorder(null);
        tfSueldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSueldoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSueldoFocusLost(evt);
            }
        });
        tfSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSueldoKeyReleased(evt);
            }
        });
        jPanel2.add(tfSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 250, -1));

        barraDorsal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(barraDorsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 290, 10));

        barraSueldo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(barraSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 290, 10));

        bJungla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png"))); // NOI18N
        bJungla.setToolTipText("Jungla");
        bJungla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJunglaMouseClicked(evt);
            }
        });
        jPanel2.add(bJungla, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 40, 50));

        bMid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png"))); // NOI18N
        bMid.setToolTipText("Mid");
        bMid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMidMouseClicked(evt);
            }
        });
        jPanel2.add(bMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 40, 50));

        bAdc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png"))); // NOI18N
        bAdc.setToolTipText("Adc");
        bAdc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAdcMouseClicked(evt);
            }
        });
        jPanel2.add(bAdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 40, 50));

        bSuplente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png"))); // NOI18N
        bSuplente.setToolTipText("Suplente");
        bSuplente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSuplenteMouseClicked(evt);
            }
        });
        jPanel2.add(bSuplente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 40, 50));

        bTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png"))); // NOI18N
        bTop.setToolTipText("Top");
        bTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTopMouseClicked(evt);
            }
        });
        jPanel2.add(bTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 40, 50));

        bSupport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png"))); // NOI18N
        bSupport.setToolTipText("Support");
        bSupport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSupportMouseClicked(evt);
            }
        });
        jPanel2.add(bSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 40, 50));

        CBequipos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBequipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona el equipo--" }));
        CBequipos.setBorder(null);
        CBequipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBequiposActionPerformed(evt);
            }
        });
        jPanel2.add(CBequipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 290, -1));

        Baceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Baceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar-white.png"))); // NOI18N
        Baceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaceptarMouseClicked(evt);
            }
        });
        jPanel2.add(Baceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        CBjugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CBjugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona Jugador--" }));
        CBjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBjugadoresActionPerformed(evt);
            }
        });
        jPanel2.add(CBjugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 320, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bJunglaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJunglaMouseClicked
       bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jungle_icon.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png"))); 
        rol="Jungla";
    }//GEN-LAST:event_bJunglaMouseClicked

    private void bTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTopMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Top_icon.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
        rol="Top";
    }//GEN-LAST:event_bTopMouseClicked

    private void bMidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMidMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Middle_icon.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
        rol="Mid";
    }//GEN-LAST:event_bMidMouseClicked

    private void bAdcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAdcMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bottom_icon.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
        rol="Adc";
    }//GEN-LAST:event_bAdcMouseClicked

    private void bSupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSupportMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Support_icon.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
        rol="Support";
    }//GEN-LAST:event_bSupportMouseClicked

    private void bSuplenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSuplenteMouseClicked
        bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
        bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
        bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
        bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
        bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
        bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill.png")));
        rol="Suplente";
    }//GEN-LAST:event_bSuplenteMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        Controlador.salir();
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setBackground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        if(modo=='o')
        {
            cerrar.setBackground(new java.awt.Color(45, 45, 45));
        }
        else
        {
            cerrar.setBackground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_cerrarMouseExited

    private void tfDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniFocusGained
       if(tfDni.getText().equals("Dni"))
        {
            tfDni.setText("");
        }
    }//GEN-LAST:event_tfDniFocusGained

    private void tfDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniFocusLost
        if(tfDni.getText().equals(""))
        {
            tfDni.setText("Dni");
            tfDni.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfDniFocusLost

    private void tfDorsalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDorsalFocusGained
       if(tfDorsal.getText().equals("Dorsal"))
        {
            tfDorsal.setText("");
        }
    }//GEN-LAST:event_tfDorsalFocusGained

    private void tfDorsalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDorsalFocusLost
        if(tfDorsal.getText().equals(""))
        {
            tfDorsal.setText("Dorsal");
            tfDorsal.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfDorsalFocusLost

    private void tfSueldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSueldoFocusGained
      if(tfSueldo.getText().equals("Sueldo"))
        {
            tfSueldo.setText("");
        }
    }//GEN-LAST:event_tfSueldoFocusGained

    private void tfSueldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSueldoFocusLost
     if(tfSueldo.getText().equals(""))
        {
            tfSueldo.setText("Sueldo");
            tfSueldo.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfSueldoFocusLost

    private void tfDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniKeyReleased
        if(validarDni(tfDni.getText()))
        {
            tfDni.setForeground(new Color(0,204,0));
            barraDni.setForeground(new Color(0,204,0));
        }
        else
        {
            tfDni.setForeground(new Color(204,0,0));
            barraDni.setForeground(new Color(204,0,0));
        }
    }//GEN-LAST:event_tfDniKeyReleased

    private void tfDorsalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDorsalKeyReleased
        if(validarDorsal(tfDorsal.getText()))
        {
            tfDorsal.setForeground(new Color(0,204,0));
            barraDorsal.setForeground(new Color(0,204,0));
        }
        else
        {
            tfDorsal.setForeground(new Color(204,0,0));
            barraDorsal.setForeground(new Color(204,0,0));
        }
    }//GEN-LAST:event_tfDorsalKeyReleased

    private void tfSueldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSueldoKeyReleased
        if(validarSueldo(tfSueldo.getText()))
        {
            tfSueldo.setForeground(new Color(0,204,0));
            barraSueldo.setForeground(new Color(0,204,0));
        }
        else
        {
            tfSueldo.setForeground(new Color(204,0,0));
            barraSueldo.setForeground(new Color(204,0,0));
        }
    }//GEN-LAST:event_tfSueldoKeyReleased

    private void CBequiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBequiposActionPerformed
        nombreEquipo=CBequipos.getSelectedItem().toString();
    }//GEN-LAST:event_CBequiposActionPerformed

    private void BaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaceptarMouseClicked
       boolean update=false;
       update=Controlador.ModificarJugador(tfDni.getText(),rol,Integer.parseInt(tfDorsal.getText()),Integer.parseInt(tfSueldo.getText()),CBequipos.getSelectedItem().toString());
       if(update==true)
           JOptionPane.showMessageDialog(this,"El jugador ha sido modificado con éxito");
       else
           JOptionPane.showMessageDialog(this,"El jugador no ha sido modificado ");
    }//GEN-LAST:event_BaceptarMouseClicked

    private void CBjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBjugadoresActionPerformed
        String [] datos=new String [7];
        datos=Controlador.DatosJugador(CBjugadores.getSelectedItem().toString());
        tfDni.setText(datos[0]);
        switch(datos[2]){
             case "JUNGLA": 
                 bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
                 bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jungle_icon.png")));
                 bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
                 bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
                 bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
                 bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png"))); 
             case "TOP": 
                 bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Top_icon.png")));
                 bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
                 bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
                 bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
                 bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
                 bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
             case "MID":
                  bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
                  bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
                  bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Middle_icon.png")));
                  bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
                  bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
                  bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
             case "ADC": 
                 bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
                 bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
                 bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
                 bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bottom_icon.png")));
                 bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
                 bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
             case "SUPPORT": 
                  bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
                  bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
                  bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
                  bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
                  bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Support_icon.png")));
                  bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill-disabled.png")));
             case "SUPLENTE":     
                 bTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-top-disabled.png")));
                 bJungla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-jungle-disabled.png")));
                 bMid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-middle-disabled.png")));
                 bAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-bottom-disabled.png")));
                 bSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-utility-disabled.png")));
                 bSuplente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-position-fill.png")));
         }
        
        
        
        tfDorsal.setText(datos[3]);
        tfSueldo.setText(datos[4]);
        CBequipos.setSelectedItem(datos[5]);
    }//GEN-LAST:event_CBjugadoresActionPerformed
      public boolean validarDni(String dni){
        Pattern patron = Pattern.compile("^([0-9]{8}[A-Z])");
        Matcher m = patron.matcher(dni);
        return m.matches();
    }
      public boolean validarDorsal(String dorsal){
        Pattern patron = Pattern.compile("^([0-9])+");
        Matcher m = patron.matcher(dorsal);
        return m.matches();
    }
      public boolean validarSueldo(String sueldo){
        Pattern patron = Pattern.compile("^([0-9]|| . || ,)+");
        if(Integer.parseInt(sueldo)>200000 || Integer.parseInt(sueldo)<950){
            tfSueldo.setForeground(new Color(204,0,0));
            barraSueldo.setForeground(new Color(204,0,0));
        }
        Matcher m = patron.matcher(sueldo);
        return m.matches();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baceptar;
    private javax.swing.JComboBox<String> CBequipos;
    private javax.swing.JComboBox<String> CBjugadores;
    private javax.swing.JLabel GifAbajo;
    private javax.swing.JLabel GifArriba;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel bAdc;
    private javax.swing.JLabel bJungla;
    private javax.swing.JLabel bMid;
    private javax.swing.JLabel bSuplente;
    private javax.swing.JLabel bSupport;
    private javax.swing.JLabel bTop;
    private javax.swing.JSeparator barraDni;
    private javax.swing.JSeparator barraDorsal;
    private javax.swing.JLabel barraDrag;
    private javax.swing.JSeparator barraSueldo;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfDorsal;
    private javax.swing.JTextField tfSueldo;
    // End of variables declaration//GEN-END:variables
}
