CREATE OR REPLACE PROCEDURE GENERAR_CALENDARIO_JORNADAS
IS
    NUMEROEQUIPOS NUMBER(3);
    X NUMBER(3):=0;
    DIASEMANA NUMBER(1);
    V_FECHA DATE;
    V_IDCAL CALENDARIOS.ID_CALENDARIO%TYPE;
BEGIN 
    SELECT COUNT(*) INTO NUMEROEQUIPOS
    FROM EQUIPOS;
    NUMEROEQUIPOS:=((numeroequipos-1)*2);
    SELECT to_number(TO_CHAR(TO_DATE(sysdate, 'DD/MM/YY'), 'D', 'NLS_DATE_LANGUAGE=SPANISH')) INTO DIASEMANA FROM DUAL;
    CASE
        WHEN DIASEMANA=1 THEN V_FECHA:=(SYSDATE+5);
        WHEN DIASEMANA=2 THEN V_FECHA:=(SYSDATE+4);
        WHEN DIASEMANA=3 THEN V_FECHA:=(SYSDATE+3);
        WHEN DIASEMANA=4 THEN V_FECHA:=(SYSDATE+2);
        WHEN DIASEMANA=5 THEN V_FECHA:=(SYSDATE+8);
        WHEN DIASEMANA=6 THEN V_FECHA:=(SYSDATE+7);
        WHEN DIASEMANA=7 THEN V_FECHA:=(SYSDATE+6);
        ELSE NULL;
    END CASE;
    
    INSERT INTO CALENDARIOS(FECHA_CIERRE,FECHA_EXPIRACION,DESCRIPCION) VALUES(SYSDATE,(V_FECHA+(7*NUMEROEQUIPOS)),'CALENDARIO LOL '||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)));
    WHILE X< NUMEROEQUIPOS LOOP
        SELECT ID_CALENDARIO INTO V_IDCAL
        FROM CALENDARIOS
        WHERE DESCRIPCION='CALENDARIO LOL '||TO_CHAR(EXTRACT(YEAR FROM SYSDATE));
        
        V_FECHA:=(V_FECHA-7);
        INSERT INTO JORNADAS(FECHA,ID_CALENDARIO) VALUES(V_FECHA,V_IDCAL);
        X:=(X+1);
    END LOOP;
END;

SET SERVEROUTPUT ON;
