CREATE PROCEDURE PARTIDOS_GANADOS_EQUIPOS(id_equipo in equipos.id_equipo%TYPE, numero_ganados OUT NUMBER)
IS
BEGIN
    SELECT COUNT(*) INTO numero_ganados
    FROM PARTIDOS
    WHERE ID_EQUIPO_GANADOR=id_equipo;
END;


CREATE OR REPLACE PROCEDURE PARTIDOS_GANADOS_TODOS_EQUIPOS(resultados OUT sys_refcursor)
IS
BEGIN
    OPEN resultados FOR
    SELECT ID_EQUIPO_GANADOR,COUNT(*) victorias
    FROM PARTIDOS
    GROUP BY ID_EQUIPO_GANADOR;
END;


CREATE OR REPLACE PROCEDURE GET_SALARIO_EQUIPO(resultados OUT NUMBER)
IS
    CURSOR C_resultados IS
    SELECT (SUM(NVL(JUGADORES.SUELDO,0))+SUM(NVL(TECNICOS.SUELDO,0)))*14 SUMA_SUELDOS
    FROM JUGADORES, TECNICOS
    WHERE TECNICOS.ID_EQUIPO=JUGADORES.ID_EQUIPO
    GROUP BY TECNICOS.ID_EQUIPO;
BEGIN
    OPEN C_resultados;
END;


CREATE OR REPLACE PROCEDURE GET_DATOS_JUGADORES(p_id_equipo in equipos.id_equipo%type, RESULTADO out sys_refcursor)
IS
BEGIN
    OPEN RESULTADO FOR
    SELECT * 
    FROM JUGADORES 
    WHERE ID_EQUIPO=P_ID_EQUIPO;
END;

CREATE OR REPLACE PACKAGE PAQUETE IS
    FUNCTION GET_NUMERO_JUGADORES_EQUIPO(F_ID_EQUIPO IN equipos.id_equipo%type) RETURN NUMBER;
END;

CREATE OR REPLACE PACKAGE BODY PAQUETE IS
    FUNCTION GET_NUMERO_JUGADORES_EQUIPO(F_ID_EQUIPO IN equipos.id_equipo%type) RETURN NUMBER
    IS
        NUMERO NUMBER(1);
    BEGIN
        
        SELECT COUNT(*) INTO NUMERO
        FROM JUGADORES
        WHERE ID_EQUIPO=F_ID_EQUIPO;
        
        RETURN NUMERO;
    END;
END PAQUETE;


