CREATE OR REPLACE PROCEDURE GENERAR_CALENDARIO_JORNADAS
IS
    NUMEROEQUIPOS NUMBER(3);
    X NUMBER(3):=0;
    DIASEMANA NUMBER(1);
    V_FECHA DATE;
    V_IDCAL CALENDARIOS.ID_CALENDARIO%TYPE;
BEGIN 
    SELECT COUNT(*) INTO NUMEROEQUIPOS
    FROM EQUIPOS;
    NUMEROEQUIPOS:=((numeroequipos-1)*2);
    SELECT to_number(TO_CHAR(TO_DATE(sysdate, 'DD/MM/YY'), 'D', 'NLS_DATE_LANGUAGE=SPANISH')) INTO DIASEMANA FROM DUAL;
    CASE
        WHEN DIASEMANA=1 THEN V_FECHA:=(SYSDATE+5);
        WHEN DIASEMANA=2 THEN V_FECHA:=(SYSDATE+4);
        WHEN DIASEMANA=3 THEN V_FECHA:=(SYSDATE+3);
        WHEN DIASEMANA=4 THEN V_FECHA:=(SYSDATE+2);
        WHEN DIASEMANA=5 THEN V_FECHA:=(SYSDATE+8);
        WHEN DIASEMANA=6 THEN V_FECHA:=(SYSDATE+7);
        WHEN DIASEMANA=7 THEN V_FECHA:=(SYSDATE+6);
        ELSE NULL;
    END CASE;
    
    INSERT INTO CALENDARIOS(FECHA_CIERRE,FECHA_EXPIRACION,DESCRIPCION) VALUES(SYSDATE,(V_FECHA+(7*NUMEROEQUIPOS)),'CALENDARIO LOL '||TO_CHAR(EXTRACT(YEAR FROM SYSDATE)));
    WHILE X< NUMEROEQUIPOS LOOP
        SELECT ID_CALENDARIO INTO V_IDCAL
        FROM CALENDARIOS
        WHERE DESCRIPCION='CALENDARIO LOL '||TO_CHAR(EXTRACT(YEAR FROM SYSDATE));
        
        V_FECHA:=(V_FECHA-7);
        INSERT INTO JORNADAS(FECHA,ID_CALENDARIO) VALUES(V_FECHA,V_IDCAL);
        X:=(X+1);
    END LOOP;
END;

CREATE PROCEDURE PARTIDOS_GANADOS_EQUIPOS(id_equipo in equipos.id_equipo%TYPE, numero_ganados OUT NUMBER)
IS
BEGIN
    SELECT COUNT(*) INTO numero_ganados
    FROM PARTIDOS
    WHERE ID_EQUIPO_GANADOR=id_equipo;
END;


CREATE OR REPLACE PROCEDURE PARTIDOS_GANADOS_TODOS_EQUIPOS(resultados OUT sys_refcursor)
IS
BEGIN
    OPEN resultados FOR
    SELECT ID_EQUIPO_GANADOR,COUNT(*) victorias
    FROM PARTIDOS
    GROUP BY ID_EQUIPO_GANADOR;
END;


CREATE OR REPLACE PROCEDURE GET_SALARIO_EQUIPO(resultados OUT NUMBER)
IS
    CURSOR C_resultados IS
    SELECT (SUM(NVL(JUGADORES.SUELDO,0))+SUM(NVL(TECNICOS.SUELDO,0)))*14 SUMA_SUELDOS
    FROM JUGADORES, TECNICOS
    WHERE TECNICOS.ID_EQUIPO=JUGADORES.ID_EQUIPO
    GROUP BY TECNICOS.ID_EQUIPO;
BEGIN
    OPEN C_resultados;
END;


CREATE OR REPLACE PROCEDURE GET_DATOS_JUGADORES(p_id_equipo in equipos.id_equipo%type, RESULTADO out sys_refcursor)
IS
BEGIN
    OPEN RESULTADO FOR
    SELECT * 
    FROM JUGADORES 
    WHERE ID_EQUIPO=P_ID_EQUIPO;
END;

CREATE OR REPLACE PACKAGE PAQUETE IS
    FUNCTION GET_NUMERO_JUGADORES_EQUIPO(F_ID_EQUIPO IN equipos.id_equipo%type) RETURN NUMBER;
END;

CREATE OR REPLACE PACKAGE BODY PAQUETE IS
    FUNCTION GET_NUMERO_JUGADORES_EQUIPO(F_ID_EQUIPO IN equipos.id_equipo%type) RETURN NUMBER
    IS
        NUMERO NUMBER(1);
    BEGIN
        
        SELECT COUNT(*) INTO NUMERO
        FROM JUGADORES
        WHERE ID_EQUIPO=F_ID_EQUIPO;
        
        RETURN NUMERO;
    END;
END PAQUETE;


