/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Equipos;

import Controlador.Controlador;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Alaitzutzu
 */
public class AltaEquipo extends javax.swing.JFrame {
private char modo;
    /**
     * Creates new form AltaEquipo
     */
    public AltaEquipo() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel2.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        barraDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GifArriba = new javax.swing.JLabel();
        GifAbajo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombreEquipo = new javax.swing.JTextField();
        tfNombreJefe = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Baceptar = new javax.swing.JLabel();
        tfApellidoJefe = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 750));
        setMinimumSize(new java.awt.Dimension(1500, 750));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setBackground(new java.awt.Color(45, 45, 45));
        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png"))); // NOI18N
        minimizar.setOpaque(true);
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarMouseExited(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 0, 30, -1));

        cerrar.setBackground(new java.awt.Color(45, 45, 45));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-white.png"))); // NOI18N
        cerrar.setOpaque(true);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 40, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(barraDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 1500, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GifArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte1.gif"))); // NOI18N
        jPanel1.add(GifArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, -1));

        GifAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte2.gif"))); // NOI18N
        jPanel1.add(GifAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 750));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alta Equipos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo-white.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefe-white.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        tfNombreEquipo.setBackground(new java.awt.Color(45, 45, 45));
        tfNombreEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombreEquipo.setForeground(new java.awt.Color(255, 255, 255));
        tfNombreEquipo.setText("Nombre Equipo");
        tfNombreEquipo.setToolTipText("Introduce el nombre del equipo");
        tfNombreEquipo.setBorder(null);
        tfNombreEquipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreEquipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreEquipoFocusLost(evt);
            }
        });
        tfNombreEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreEquipoKeyTyped(evt);
            }
        });
        jPanel2.add(tfNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 250, 30));

        tfNombreJefe.setBackground(new java.awt.Color(45, 45, 45));
        tfNombreJefe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombreJefe.setForeground(new java.awt.Color(255, 255, 255));
        tfNombreJefe.setText("Nombre del Jefe");
        tfNombreJefe.setToolTipText("Introduce el id del jefe");
        tfNombreJefe.setBorder(null);
        tfNombreJefe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreJefeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreJefeFocusLost(evt);
            }
        });
        tfNombreJefe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreJefeKeyTyped(evt);
            }
        });
        jPanel2.add(tfNombreJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 250, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 260, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 260, 10));

        Baceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Baceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar-white.png"))); // NOI18N
        Baceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaceptarMouseClicked(evt);
            }
        });
        jPanel2.add(Baceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 150, 60));

        tfApellidoJefe.setBackground(new java.awt.Color(45, 45, 45));
        tfApellidoJefe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfApellidoJefe.setForeground(new java.awt.Color(255, 255, 255));
        tfApellidoJefe.setText("Apellido del Jefe");
        tfApellidoJefe.setToolTipText("Introduce el apellido del jefe");
        tfApellidoJefe.setBorder(null);
        tfApellidoJefe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfApellidoJefeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfApellidoJefeFocusLost(evt);
            }
        });
        tfApellidoJefe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoJefeKeyTyped(evt);
            }
        });
        jPanel2.add(tfApellidoJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 260, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 260, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        Controlador.salir();
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void minimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseEntered
        if(modo=='o')
        {
            minimizar.setBackground(new Color(255,255,255,50));
        }
        else
        {
            minimizar.setBackground(new Color(0,0,0,50));
        }
    }//GEN-LAST:event_minimizarMouseEntered

    private void minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseExited
         if(modo=='o')
        {
            minimizar.setBackground(new java.awt.Color(45, 45, 45));
        }
        else
        {
            minimizar.setBackground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_minimizarMouseExited

    private void BaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaceptarMouseClicked
        int id=0;
        boolean insertado=false;
        id=Controlador.ComprobarJefe(tfNombreJefe.getText(),tfApellidoJefe.getText());
        if(id == 0){
             JOptionPane.showMessageDialog(this,"No se ha encontrado ningún Jefe con ese nombre y apellido");  
        }
        else
             insertado=Controlador.AltaEquipo(tfNombreEquipo.getText(),tfNombreJefe.getText(),tfApellidoJefe.getText());
        if(insertado==true)
            JOptionPane.showMessageDialog(this,"El equipo se ha insertado correctamente");
        else
            JOptionPane.showMessageDialog(this,"El equipo no se ha insertado correctamente");
    }//GEN-LAST:event_BaceptarMouseClicked

    private void tfNombreEquipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreEquipoKeyTyped
       
                if(validarNombreEquipo(tfNombreEquipo.getText()))
            {
                tfNombreEquipo.setForeground(new Color(0,204,0));
                tfNombreEquipo.setForeground(new Color(0,204,0));
            }
            else
            {
                tfNombreEquipo.setForeground(new Color(204,0,0));
                tfNombreEquipo.setForeground(new Color(204,0,0));
            }
       
       
    }//GEN-LAST:event_tfNombreEquipoKeyTyped

    private void tfNombreJefeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreJefeKeyTyped

            if(validarNombreJefe(tfNombreJefe.getText()))
            {
                tfNombreJefe.setForeground(new Color(0,204,0));
                tfNombreJefe.setForeground(new Color(0,204,0));
            }
            else
            {
                tfNombreJefe.setForeground(new Color(204,0,0));
                tfNombreJefe.setForeground(new Color(204,0,0));
            }
            
            
       
    }//GEN-LAST:event_tfNombreJefeKeyTyped

    private void tfApellidoJefeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoJefeKeyTyped
         if(validarApellidoJefe(tfApellidoJefe.getText()))
            {
                tfApellidoJefe.setForeground(new Color(0,204,0));
                tfApellidoJefe.setForeground(new Color(0,204,0));
            }
            else
            {
                tfApellidoJefe.setForeground(new Color(204,0,0));
                tfApellidoJefe.setForeground(new Color(204,0,0));
            }
    }//GEN-LAST:event_tfApellidoJefeKeyTyped

    private void tfNombreEquipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreEquipoFocusGained
        if(tfNombreEquipo.getText().equals("Nombre Equipo"))
        {
            tfNombreEquipo.setText("");
        }
    }//GEN-LAST:event_tfNombreEquipoFocusGained

    private void tfNombreJefeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreJefeFocusGained
        if(tfNombreJefe.getText().equals("Nombre del Jefe"))
        {
            tfNombreJefe.setText("");
        }
    }//GEN-LAST:event_tfNombreJefeFocusGained

    private void tfApellidoJefeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfApellidoJefeFocusGained
        if(tfApellidoJefe.getText().equals("Apellido del Jefe"))
        {
            tfApellidoJefe.setText("");
        }
    }//GEN-LAST:event_tfApellidoJefeFocusGained

    private void tfNombreEquipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreEquipoFocusLost
      if(tfNombreEquipo.getText().equals(""))
        {
            tfNombreEquipo.setText("Nombre Equipo");
            tfNombreEquipo.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfNombreEquipoFocusLost

    private void tfNombreJefeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreJefeFocusLost
       if(tfNombreJefe.getText().equals(""))
        {
            tfNombreJefe.setText("Nombre del Jefe");
            tfNombreJefe.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfNombreJefeFocusLost

    private void tfApellidoJefeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfApellidoJefeFocusLost
        if(tfApellidoJefe.getText().equals(""))
        {
            tfApellidoJefe.setText("Apellido del Jefe");
            tfApellidoJefe.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfApellidoJefeFocusLost
    public boolean validarNombreEquipo(String nombreEquipo){
        Pattern patron = Pattern.compile("^(([A-Z]||[a-z]||[0-9])||´)+$");
        Matcher m = patron.matcher(nombreEquipo);
        return m.matches();
    }
     public boolean validarApellidoJefe(String apellidoJefe){
        Pattern patron = Pattern.compile("^([A-Z]||[a-z]||[0-9])+$");
        Matcher m = patron.matcher(apellidoJefe);
        return m.matches();
    }
     public boolean validarNombreJefe(String nombreJefe){
        Pattern patron = Pattern.compile("^([A-Z]||[a-z]||[0-9])+$");
        Matcher m = patron.matcher(nombreJefe);
        return m.matches();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baceptar;
    private javax.swing.JLabel GifAbajo;
    private javax.swing.JLabel GifArriba;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel barraDrag;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel minimizar;
    private javax.swing.JTextField tfApellidoJefe;
    private javax.swing.JTextField tfNombreEquipo;
    private javax.swing.JTextField tfNombreJefe;
    // End of variables declaration//GEN-END:variables
}
