/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Equipos;

import AppPackage.AnimationClass;
import Controlador.Controlador;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alaitzutzu
 */
public class ModifEquipo extends javax.swing.JFrame {
private int xMouse;
private int yMouse;
private char modo;
private static String [] d;
private AnimationClass animacion = new AnimationClass();
private boolean menuAbierto=false;
private boolean listaDesplegableAlta=false;
private boolean listaDesplegableBaja=false;
private boolean listaDesplegableModificaciones=false;
private ArrayList<javax.swing.JLabel>listaLabelsComboBox=new ArrayList();

    /**
     * Creates new form AltaEquipo
     * @param d
     */
    public ModifEquipo(String [] d) {
        initComponents();
        setLocationRelativeTo(null);
        jPanel2.requestFocus();
        tfIdEquipo.setText(d[0]);
        tfNombre.setText(d[1]);
        tfIdJefe.setText(d[2]);
        menu.setBackground(new Color (45,45,45,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bMinimizar = new javax.swing.JLabel();
        bCerrar = new javax.swing.JLabel();
        barraDrag = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bMenu = new javax.swing.JLabel();
        bModo = new javax.swing.JLabel();
        bAlta = new javax.swing.JLabel();
        bAltaEquipos = new javax.swing.JLabel();
        bAltaJugadores = new javax.swing.JLabel();
        bAltaJefes = new javax.swing.JLabel();
        bAltaUsuarios = new javax.swing.JLabel();
        bBaja = new javax.swing.JLabel();
        bBajaEquipos = new javax.swing.JLabel();
        bBajaJugadores = new javax.swing.JLabel();
        bBajaJefes = new javax.swing.JLabel();
        bBajaUsuarios = new javax.swing.JLabel();
        bModificacion = new javax.swing.JLabel();
        bModificacionEquipos = new javax.swing.JLabel();
        bModificacionJugadores = new javax.swing.JLabel();
        bModificacionJefes = new javax.swing.JLabel();
        bModificacionUsuarios = new javax.swing.JLabel();
        bCalendario = new javax.swing.JLabel();
        bRealizarEmparejamientos = new javax.swing.JLabel();
        bResultadosJornada = new javax.swing.JLabel();
        bClasificacionGeneral = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        gifAbajo = new javax.swing.JLabel();
        GIFarriba = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfIdEquipo = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfIdJefe = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        bAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 750));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png"))); // NOI18N
        bMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMinimizarMouseExited(evt);
            }
        });
        getContentPane().add(bMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 0, 40, -1));

        bCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-white.png"))); // NOI18N
        bCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 40, -1));

        barraDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraDragMouseDragged(evt);
            }
        });
        barraDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraDragMousePressed(evt);
            }
        });
        getContentPane().add(barraDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        bMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMenuMouseClicked(evt);
            }
        });
        jPanel1.add(bMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 50));

        bModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luna.png"))); // NOI18N
        bModo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModoMouseClicked(evt);
            }
        });
        jPanel1.add(bModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 60, 40, 40));

        bAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAlta.setForeground(new java.awt.Color(255, 255, 255));
        bAlta.setText("     Alta");
        bAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAltaMouseClicked(evt);
            }
        });
        jPanel1.add(bAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 110, 300, 30));

        bAltaEquipos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bAltaEquipos.setForeground(new java.awt.Color(255, 255, 255));
        bAltaEquipos.setText("           Equipos");
        bAltaEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAltaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAltaEquiposMouseClicked(evt);
            }
        });
        jPanel1.add(bAltaEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 150, 300, 30));

        bAltaJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bAltaJugadores.setForeground(new java.awt.Color(255, 255, 255));
        bAltaJugadores.setText("           Jugadores");
        bAltaJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAltaJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAltaJugadoresMouseClicked(evt);
            }
        });
        jPanel1.add(bAltaJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 190, 300, 30));

        bAltaJefes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bAltaJefes.setForeground(new java.awt.Color(255, 255, 255));
        bAltaJefes.setText("           Jefes");
        bAltaJefes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bAltaJefes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 230, 300, 30));

        bAltaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bAltaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        bAltaUsuarios.setText("           Usuarios");
        bAltaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bAltaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 270, 300, 30));

        bBaja.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bBaja.setForeground(new java.awt.Color(255, 255, 255));
        bBaja.setText("     Baja");
        bBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBajaMouseClicked(evt);
            }
        });
        jPanel1.add(bBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 150, 300, 30));

        bBajaEquipos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBajaEquipos.setForeground(new java.awt.Color(255, 255, 255));
        bBajaEquipos.setText("           Equipos");
        bBajaEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBajaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBajaEquiposMouseClicked(evt);
            }
        });
        jPanel1.add(bBajaEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 190, 300, 30));

        bBajaJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBajaJugadores.setForeground(new java.awt.Color(255, 255, 255));
        bBajaJugadores.setText("           Jugadores");
        bBajaJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBajaJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBajaJugadoresMouseClicked(evt);
            }
        });
        jPanel1.add(bBajaJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 230, 300, 30));

        bBajaJefes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBajaJefes.setForeground(new java.awt.Color(255, 255, 255));
        bBajaJefes.setText("           Jefes");
        bBajaJefes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bBajaJefes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 270, 300, 30));

        bBajaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bBajaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        bBajaUsuarios.setText("           Usuarios");
        bBajaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bBajaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 310, 300, 30));

        bModificacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bModificacion.setForeground(new java.awt.Color(255, 255, 255));
        bModificacion.setText("     Modificación");
        bModificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModificacionMouseClicked(evt);
            }
        });
        jPanel1.add(bModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 190, 300, 30));

        bModificacionEquipos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bModificacionEquipos.setForeground(new java.awt.Color(255, 255, 255));
        bModificacionEquipos.setText("           Equipos");
        bModificacionEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModificacionEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModificacionEquiposMouseClicked(evt);
            }
        });
        jPanel1.add(bModificacionEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 230, 300, 30));

        bModificacionJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bModificacionJugadores.setForeground(new java.awt.Color(255, 255, 255));
        bModificacionJugadores.setText("           Jugadores");
        bModificacionJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bModificacionJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 270, 300, 30));

        bModificacionJefes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bModificacionJefes.setForeground(new java.awt.Color(255, 255, 255));
        bModificacionJefes.setText("           Jefes");
        bModificacionJefes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bModificacionJefes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 310, 300, 30));

        bModificacionUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bModificacionUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        bModificacionUsuarios.setText("           Usuarios");
        bModificacionUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bModificacionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 350, 300, 30));

        bCalendario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bCalendario.setForeground(new java.awt.Color(255, 255, 255));
        bCalendario.setText("     Calendario");
        bCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 230, 300, 30));

        bRealizarEmparejamientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bRealizarEmparejamientos.setForeground(new java.awt.Color(255, 255, 255));
        bRealizarEmparejamientos.setText("     Realizar Emparejamientos");
        bRealizarEmparejamientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bRealizarEmparejamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 270, 300, 30));

        bResultadosJornada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bResultadosJornada.setForeground(new java.awt.Color(255, 255, 255));
        bResultadosJornada.setText("     Resultados Jornada");
        bResultadosJornada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bResultadosJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 310, 300, 30));

        bClasificacionGeneral.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bClasificacionGeneral.setForeground(new java.awt.Color(255, 255, 255));
        bClasificacionGeneral.setText("     Clasificación general");
        bClasificacionGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(bClasificacionGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 350, 300, 30));

        menu.setBackground(new java.awt.Color(120, 120, 120));
        menu.setOpaque(true);
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 50, 300, 700));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO-small.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        gifAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte2.gif"))); // NOI18N
        jPanel1.add(gifAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 500, 500));

        GIFarriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GIF3Parte1.gif"))); // NOI18N
        jPanel1.add(GIFarriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 500, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 750));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setText("Modificacion Equipos");
        jPanel2.add(lTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo-white.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camiseta-white.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jefe-white.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 30, 30));

        tfIdEquipo.setEditable(false);
        tfIdEquipo.setBackground(new java.awt.Color(45, 45, 45));
        tfIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIdEquipo.setForeground(new java.awt.Color(255, 255, 255));
        tfIdEquipo.setText("Nombre Equipo");
        tfIdEquipo.setToolTipText("Introduce el ID del equipo");
        tfIdEquipo.setBorder(null);
        tfIdEquipo.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(tfIdEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 690, 50));

        tfNombre.setEditable(false);
        tfNombre.setBackground(new java.awt.Color(45, 45, 45));
        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        tfNombre.setText("Nombre Equipo");
        tfNombre.setToolTipText("Introduce el nombre del equipo");
        tfNombre.setBorder(null);
        tfNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });
        jPanel2.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 690, 50));

        tfIdJefe.setBackground(new java.awt.Color(45, 45, 45));
        tfIdJefe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIdJefe.setForeground(new java.awt.Color(255, 255, 255));
        tfIdJefe.setText("ID Jefe");
        tfIdJefe.setToolTipText("Introduce el id del jefe");
        tfIdJefe.setBorder(null);
        tfIdJefe.setCaretColor(new java.awt.Color(255, 255, 255));
        tfIdJefe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIdJefeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIdJefeFocusLost(evt);
            }
        });
        jPanel2.add(tfIdJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 690, 50));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 690, 1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 690, 1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 690, 1));

        bAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar-white.png"))); // NOI18N
        bAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAceptarMouseClicked(evt);
            }
        });
        jPanel2.add(bAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        if(tfNombre.getText().equals("Nombre Equipo")|| tfNombre.getText().equals(d[1]))
        {
            tfNombre.setText("");
        }
    }//GEN-LAST:event_tfNombreFocusGained

    private void tfIdJefeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdJefeFocusGained
       if(tfIdJefe.getText().equals("ID Jefe")|| tfIdJefe.getText().equals(d[2]))
        {
            tfIdJefe.setText("");
        }
    }//GEN-LAST:event_tfIdJefeFocusGained

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
       if(tfNombre.getText().equals(""))
        {
            tfNombre.setText(d[1]);
            tfNombre.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfNombreFocusLost

    private void tfIdJefeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdJefeFocusLost
         if(tfIdJefe.getText().equals(""))
        {
            tfIdJefe.setText(d[2]);
            tfIdJefe.setForeground(new Color(255,255,255));
            
        }
    }//GEN-LAST:event_tfIdJefeFocusLost

    private void bCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarMouseClicked
        Controlador.salir();
    }//GEN-LAST:event_bCerrarMouseClicked

    private void bMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinimizarMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_bMinimizarMouseClicked

    private void barraDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraDragMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_barraDragMousePressed

    private void barraDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraDragMouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraDragMouseDragged

    private void bMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinimizarMouseEntered
       if(modo=='o')
        {
            bMinimizar.setBackground(new Color(255,255,255,50));
        }
        else
        {
            bMinimizar.setBackground(new Color(0,0,0,50));
        }
    }//GEN-LAST:event_bMinimizarMouseEntered

    private void bMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinimizarMouseExited
         if(modo=='o')
        {
            bMinimizar.setBackground(new java.awt.Color(45, 45, 45));
        }
        else
        {
            bMinimizar.setBackground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_bMinimizarMouseExited

    private void bAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAceptarMouseClicked
        String n=null;
        int i=0;
        boolean modificar=false;
        if(tfNombre.getText().equals(d[1])&& tfIdJefe.getText() != d[2])
            modificar=Controlador.ModificarEquipo(n,Integer.parseInt(tfIdJefe.getText()),Integer.parseInt(d[0]));
        else
            if(tfNombre.getText().equals(d[1])&& tfIdJefe.getText().equals(d[2]))
                JOptionPane.showMessageDialog(this,"No se ha echo ningun cambio");
            else
            {
                modificar=Controlador.ModificarEquipo(tfNombre.getText(),i,Integer.parseInt(d[0]));
            }
    
    }//GEN-LAST:event_bAceptarMouseClicked

    private void bMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMenuMouseClicked
        if(menuAbierto){
            menuAbierto=false;
            if(listaDesplegableAlta)
            {
                bAltaMouseClicked(evt);
            }
            else if(listaDesplegableBaja)
            {
                bBajaMouseClicked(evt);
            }
            else if (listaDesplegableModificaciones)
            {
                bModificacionMouseClicked(evt);
            }
            animacion.jLabelXLeft(menu.getX(), menu.getX()-300, 3, 5, menu);
            animacion.jLabelXLeft(bAlta.getX(),bAlta.getX()-300, 3, 5, bAlta);
            animacion.jLabelXLeft(bBaja.getX(),bBaja.getX()-300, 3, 5, bBaja);
            animacion.jLabelXLeft(bModificacion.getX(),bModificacion.getX()-300, 3, 5, bModificacion);
            animacion.jLabelXLeft(bCalendario.getX(),bCalendario.getX()-300, 3, 5, bCalendario);
            animacion.jLabelXLeft(bRealizarEmparejamientos.getX(),bRealizarEmparejamientos.getX()-300, 3, 5, bRealizarEmparejamientos);
            animacion.jLabelXLeft(bResultadosJornada.getX(),bResultadosJornada.getX()-300, 3, 5, bResultadosJornada);
            animacion.jLabelXLeft(bClasificacionGeneral.getX(),bClasificacionGeneral.getX()-300, 3, 5, bClasificacionGeneral);
            animacion.jLabelXLeft(bModo.getX(), bModo.getX()-300, 3, 5, bModo);
        }
        else{
            bAlta.setLocation(-300, 110);
            bBaja.setLocation(-300, 150);
            bModificacion.setLocation(-300, 190);
            bCalendario.setLocation(-300, 230);
            bRealizarEmparejamientos.setLocation(-300, 270);
            bResultadosJornada.setLocation(-300, 310);
            bClasificacionGeneral.setLocation(-300, 350);
            menuAbierto=true;
            animacion.jLabelXRight(menu.getX(), menu.getX()+300, 3, 5, menu);
            animacion.jLabelXRight(bAlta.getX(),bAlta.getX()+300, 3, 5, bAlta);
            animacion.jLabelXRight(bBaja.getX(),bBaja.getX()+300, 3, 5, bBaja);
            animacion.jLabelXRight(bModificacion.getX(),bModificacion.getX()+300, 3, 5, bModificacion);
            animacion.jLabelXRight(bCalendario.getX(),bCalendario.getX()+300, 3, 5, bCalendario);
            animacion.jLabelXRight(bRealizarEmparejamientos.getX(),bRealizarEmparejamientos.getX()+300, 3, 5, bRealizarEmparejamientos);
            animacion.jLabelXRight(bResultadosJornada.getX(),bResultadosJornada.getX()+300, 3, 5, bResultadosJornada);
            animacion.jLabelXRight(bClasificacionGeneral.getX(),bClasificacionGeneral.getX()+300, 3, 5, bClasificacionGeneral);
            animacion.jLabelXRight(bModo.getX(), bModo.getX()+300, 3, 5, bModo);
        }
    }//GEN-LAST:event_bMenuMouseClicked

    private void bModoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModoMouseClicked
        if(modo==('o')){
            modo='c';
            bModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sol.png")));
            bCerrar.setBackground(new java.awt.Color(255,255,255));
            bMinimizar.setBackground(new java.awt.Color(255,255,255));
            bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png")));
            bMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png")));
            bMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-negro.png")));
            jPanel2.setBackground(new Color(255,255,255));
            lTitulo.setForeground(new Color(0,0,0));
            menu.setBackground(new Color (255,255,255,200));
            bAlta.setForeground(new Color(0,0,0));
            bBaja.setForeground(new Color(0,0,0));
            bModificacion.setForeground(new Color(0,0,0));
            bCalendario.setForeground(new Color(0,0,0));
            bRealizarEmparejamientos.setForeground(new Color(0,0,0));
            bResultadosJornada.setForeground(new Color(0,0,0));
            bClasificacionGeneral.setForeground(new Color(0,0,0));
            bBajaEquipos.setForeground(new Color(0,0,0));
            bBajaJugadores.setForeground(new Color(0,0,0));
            bBajaJefes.setForeground(new Color(0,0,0));
            bBajaUsuarios.setForeground(new Color(0,0,0));
            bModificacionEquipos.setForeground(new Color(0,0,0));
            bModificacionJugadores.setForeground(new Color(0,0,0));
            bModificacionJefes.setForeground(new Color(0,0,0));
            bModificacionUsuarios.setForeground(new Color(0,0,0));
            bAltaEquipos.setForeground(new Color(0,0,0));
            bAltaJugadores.setForeground(new Color(0,0,0));
            bAltaJefes.setForeground(new Color(0,0,0));
            bAltaUsuarios.setForeground(new Color(0,0,0));
            bBajaEquipos.setForeground(new Color(0,0,0));
            bBajaJugadores.setForeground(new Color(0,0,0));
            bBajaJefes.setForeground(new Color(0,0,0));
            bBajaUsuarios.setForeground(new Color(0,0,0));
            bModificacionEquipos.setForeground(new Color(0,0,0));
            bModificacionJugadores.setForeground(new Color(0,0,0));
            bModificacionJefes.setForeground(new Color(0,0,0));
            bModificacionUsuarios.setForeground(new Color(0,0,0));
        }
        else{
            modo='o';
            bModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/luna.png")));
            bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-white.png")));
            bCerrar.setBackground(new java.awt.Color(45,45,45));
            bMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar-white.png")));
            bMinimizar.setBackground(new java.awt.Color(45,45,45));
            bMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png")));
            jPanel2.setBackground(new Color(45,45,45));
            lTitulo.setForeground(new Color(255,255,255));
            menu.setBackground(new Color (45,45,45,200));
            bAlta.setForeground(new Color(255,255,255));
            bBaja.setForeground(new Color(255,255,255));
            bModificacion.setForeground(new Color(255,255,255));
            bCalendario.setForeground(new Color(255,255,255));
            bRealizarEmparejamientos.setForeground(new Color(255,255,255));
            bResultadosJornada.setForeground(new Color(255,255,255));
            bClasificacionGeneral.setForeground(new Color(255,255,255));
            bBajaEquipos.setForeground(new Color(255,255,255));
            bBajaJugadores.setForeground(new Color(255,255,255));
            bBajaJefes.setForeground(new Color(255,255,255));
            bBajaUsuarios.setForeground(new Color(255,255,255));
            bModificacionEquipos.setForeground(new Color(255,255,255));
            bModificacionJugadores.setForeground(new Color(255,255,255));
            bModificacionJefes.setForeground(new Color(255,255,255));
            bModificacionUsuarios.setForeground(new Color(255,255,255));
            bAltaEquipos.setForeground(new Color(255,255,255));
            bAltaJugadores.setForeground(new Color(255,255,255));
            bAltaJefes.setForeground(new Color(255,255,255));
            bAltaUsuarios.setForeground(new Color(255,255,255));
            bBajaEquipos.setForeground(new Color(255,255,255));
            bBajaJugadores.setForeground(new Color(255,255,255));
            bBajaJefes.setForeground(new Color(255,255,255));
            bBajaUsuarios.setForeground(new Color(255,255,255));
            bModificacionEquipos.setForeground(new Color(255,255,255));
            bModificacionJugadores.setForeground(new Color(255,255,255));
            bModificacionJefes.setForeground(new Color(255,255,255));
            bModificacionUsuarios.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_bModoMouseClicked

    private void ocultarSubmenu(int eleccion)
    {
        switch(eleccion)
        {
            case 1:
                animacion.jLabelXLeft(bAltaEquipos.getX(), bAltaEquipos.getX()-300, 3, 5, bAltaEquipos);
                animacion.jLabelXLeft(bAltaJugadores.getX(), bAltaJugadores.getX()-300, 3, 5, bAltaJugadores);
                animacion.jLabelXLeft(bAltaJefes.getX(), bAltaJefes.getX()-300, 3, 5, bAltaJefes);
                animacion.jLabelXLeft(bAltaUsuarios.getX(), bAltaUsuarios.getX()-300, 3, 5, bAltaUsuarios);
                break;
            case 2:
                animacion.jLabelXLeft(bBajaEquipos.getX(), bBajaEquipos.getX()-300, 3, 5, bBajaEquipos);
                animacion.jLabelXLeft(bBajaJugadores.getX(), bBajaJugadores.getX()-300, 3, 5, bBajaJugadores);
                animacion.jLabelXLeft(bBajaJefes.getX(), bBajaJefes.getX()-300, 3, 5, bBajaJefes);
                animacion.jLabelXLeft(bBajaUsuarios.getX(), bBajaUsuarios.getX()-300, 3, 5, bBajaUsuarios);
                break;
            case 3:
                animacion.jLabelXLeft(bModificacionEquipos.getX(), bModificacionEquipos.getX()-300, 3, 5, bModificacionEquipos);
                animacion.jLabelXLeft(bModificacionJugadores.getX(), bModificacionJugadores.getX()-300, 3, 5, bModificacionJugadores);
                animacion.jLabelXLeft(bModificacionJefes.getX(), bModificacionJefes.getX()-300, 3, 5, bModificacionJefes);
                animacion.jLabelXLeft(bModificacionUsuarios.getX(), bModificacionUsuarios.getX()-300, 3, 5, bModificacionUsuarios);
                break;
        }
    }
    
    private void bAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAltaMouseClicked
        if(listaDesplegableAlta){
            listaDesplegableAlta=false;
            animacion.jLabelYUp(bBaja.getY(), bBaja.getY()-160, 3, 5, bBaja);
            animacion.jLabelYUp(bModificacion.getY(), bModificacion.getY()-160, 3, 5, bModificacion);
            animacion.jLabelYUp(bCalendario.getY(), bCalendario.getY()-160, 3, 5, bCalendario);
            animacion.jLabelYUp(bRealizarEmparejamientos.getY(), bRealizarEmparejamientos.getY()-160, 3, 5, bRealizarEmparejamientos);
            animacion.jLabelYUp(bResultadosJornada.getY(), bResultadosJornada.getY()-160, 3, 5, bResultadosJornada);
            animacion.jLabelYUp(bClasificacionGeneral.getY(), bClasificacionGeneral.getY()-160, 3, 5, bClasificacionGeneral);

            ocultarSubmenu(1);
        }
        else{
            listaDesplegableAlta=true;
            if(listaDesplegableBaja)
            {
                listaDesplegableBaja=false;
                ocultarSubmenu(2);

                animacion.jLabelYDown(bBaja.getY(), bBaja.getY()+160, 3, 5, bBaja);
            }else if(listaDesplegableModificaciones)
            {
                listaDesplegableModificaciones=false;
                ocultarSubmenu(3);

                animacion.jLabelYDown(bModificacion.getY(), bModificacion.getY()+160, 3, 5, bModificacion);
                animacion.jLabelYDown(bBaja.getY(), bBaja.getY()+160, 3, 5, bBaja);
            }
            else
            {
                animacion.jLabelYDown(bBaja.getY(), bBaja.getY()+160, 3, 5, bBaja);
                animacion.jLabelYDown(bModificacion.getY(), bModificacion.getY()+160, 3, 5, bModificacion);
                animacion.jLabelYDown(bCalendario.getY(), bCalendario.getY()+160, 3, 5, bCalendario);
                animacion.jLabelYDown(bRealizarEmparejamientos.getY(), bRealizarEmparejamientos.getY()+160, 3, 5, bRealizarEmparejamientos);
                animacion.jLabelYDown(bResultadosJornada.getY(), bResultadosJornada.getY()+160, 3, 5, bResultadosJornada);
                animacion.jLabelYDown(bClasificacionGeneral.getY(), bClasificacionGeneral.getY()+160, 3, 5, bClasificacionGeneral);
            }
            animacion.jLabelXRight(bAltaEquipos.getX(), bAltaEquipos.getX()+300, 3, 5, bAltaEquipos);
            animacion.jLabelXRight(bAltaJugadores.getX(), bAltaJugadores.getX()+300, 3, 5, bAltaJugadores);
            animacion.jLabelXRight(bAltaJefes.getX(), bAltaJefes.getX()+300, 3, 5, bAltaJefes);
            animacion.jLabelXRight(bAltaUsuarios.getX(), bAltaUsuarios.getX()+300, 3, 5, bAltaUsuarios);
        }
    }//GEN-LAST:event_bAltaMouseClicked

    private void bAltaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAltaEquiposMouseClicked
        Controlador.VentanaAltaEquipo(this);
    }//GEN-LAST:event_bAltaEquiposMouseClicked

    private void bAltaJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAltaJugadoresMouseClicked
        Controlador.VentanaAltaJugador(this);
    }//GEN-LAST:event_bAltaJugadoresMouseClicked

    private void bBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBajaMouseClicked
        if(listaDesplegableBaja){
            listaDesplegableBaja=false;
            animacion.jLabelYUp(bModificacion.getY(), bModificacion.getY()-160, 3, 5, bModificacion);
            animacion.jLabelYUp(bCalendario.getY(), bCalendario.getY()-160, 3, 5, bCalendario);
            animacion.jLabelYUp(bRealizarEmparejamientos.getY(), bRealizarEmparejamientos.getY()-160, 3, 5, bRealizarEmparejamientos);
            animacion.jLabelYUp(bResultadosJornada.getY(), bResultadosJornada.getY()-160, 3, 5, bResultadosJornada);
            animacion.jLabelYUp(bClasificacionGeneral.getY(), bClasificacionGeneral.getY()-160, 3, 5, bClasificacionGeneral);

            animacion.jLabelXLeft(bBajaEquipos.getX(), bBajaEquipos.getX()-300, 3, 5, bBajaEquipos);
            animacion.jLabelXLeft(bBajaJugadores.getX(), bBajaJugadores.getX()-300, 3, 5, bBajaJugadores);
            animacion.jLabelXLeft(bBajaJefes.getX(), bBajaJefes.getX()-300, 3, 5, bBajaJefes);
            animacion.jLabelXLeft(bBajaUsuarios.getX(), bBajaUsuarios.getX()-300, 3, 5, bBajaUsuarios);
        }
        else{
            listaDesplegableBaja=true;
            if(listaDesplegableAlta)
            {
                listaDesplegableAlta=false;
                animacion.jLabelXLeft(bAltaEquipos.getX(), bAltaEquipos.getX()-300, 3, 5, bAltaEquipos);
                animacion.jLabelXLeft(bAltaJugadores.getX(), bAltaJugadores.getX()-300, 3, 5, bAltaJugadores);
                animacion.jLabelXLeft(bAltaJefes.getX(), bAltaJefes.getX()-300, 3, 5, bAltaJefes);
                animacion.jLabelXLeft(bAltaUsuarios.getX(), bAltaUsuarios.getX()-300, 3, 5, bAltaUsuarios);

                animacion.jLabelYUp(bBaja.getY(), bBaja.getY()-160, 3, 5, bBaja);

                animacion.jLabelXRight(bBajaEquipos.getX(), bBajaEquipos.getX()+300, 3, 5, bBajaEquipos);
                animacion.jLabelXRight(bBajaJugadores.getX(), bBajaJugadores.getX()+300, 3, 5, bBajaJugadores);
                animacion.jLabelXRight(bBajaJefes.getX(), bBajaJefes.getX()+300, 3, 5, bBajaJefes);
                animacion.jLabelXRight(bBajaUsuarios.getX(), bBajaUsuarios.getX()+300, 3, 5, bBajaUsuarios);
            }else if(listaDesplegableModificaciones)
            {
                listaDesplegableModificaciones=false;
                animacion.jLabelXLeft(bModificacionEquipos.getX(), bModificacionEquipos.getX()-300, 3, 5, bModificacionEquipos);
                animacion.jLabelXLeft(bModificacionJugadores.getX(), bModificacionJugadores.getX()-300, 3, 5, bModificacionJugadores);
                animacion.jLabelXLeft(bModificacionJefes.getX(), bModificacionJefes.getX()-300, 3, 5, bModificacionJefes);
                animacion.jLabelXLeft(bModificacionUsuarios.getX(), bModificacionUsuarios.getX()-300, 3, 5, bModificacionUsuarios);

                animacion.jLabelYDown(bModificacion.getY(), bModificacion.getY()+160, 3, 5, bModificacion);

                animacion.jLabelXRight(bBajaEquipos.getX(), bBajaEquipos.getX()+300, 3, 5, bBajaEquipos);
                animacion.jLabelXRight(bBajaJugadores.getX(), bBajaJugadores.getX()+300, 3, 5, bBajaJugadores);
                animacion.jLabelXRight(bBajaJefes.getX(), bBajaJefes.getX()+300, 3, 5, bBajaJefes);
                animacion.jLabelXRight(bBajaUsuarios.getX(), bBajaUsuarios.getX()+300, 3, 5, bBajaUsuarios);
            }
            else
            {
                animacion.jLabelYDown(bModificacion.getY(), bModificacion.getY()+160, 3, 5, bModificacion);
                animacion.jLabelYDown(bCalendario.getY(), bCalendario.getY()+160, 3, 5, bCalendario);
                animacion.jLabelYDown(bRealizarEmparejamientos.getY(), bRealizarEmparejamientos.getY()+160, 3, 5, bRealizarEmparejamientos);
                animacion.jLabelYDown(bResultadosJornada.getY(), bResultadosJornada.getY()+160, 3, 5, bResultadosJornada);
                animacion.jLabelYDown(bClasificacionGeneral.getY(), bClasificacionGeneral.getY()+160, 3, 5, bClasificacionGeneral);

                animacion.jLabelXRight(bBajaEquipos.getX(), bBajaEquipos.getX()+300, 3, 5, bBajaEquipos);
                animacion.jLabelXRight(bBajaJugadores.getX(), bBajaJugadores.getX()+300, 3, 5, bBajaJugadores);
                animacion.jLabelXRight(bBajaJefes.getX(), bBajaJefes.getX()+300, 3, 5, bBajaJefes);
                animacion.jLabelXRight(bBajaUsuarios.getX(), bBajaUsuarios.getX()+300, 3, 5, bBajaUsuarios);
            }
        }
    }//GEN-LAST:event_bBajaMouseClicked

    private void bBajaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBajaEquiposMouseClicked
        Controlador.VentanaBajaEquipo(this);
    }//GEN-LAST:event_bBajaEquiposMouseClicked

    private void bBajaJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBajaJugadoresMouseClicked
        Controlador.VentanaBajaJugador(this);
    }//GEN-LAST:event_bBajaJugadoresMouseClicked

    private void bModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModificacionMouseClicked
        if(listaDesplegableModificaciones){
            listaDesplegableModificaciones=false;
            animacion.jLabelYUp(bCalendario.getY(), bCalendario.getY()-160, 3, 5, bCalendario);
            animacion.jLabelYUp(bRealizarEmparejamientos.getY(), bRealizarEmparejamientos.getY()-160, 3, 5, bRealizarEmparejamientos);
            animacion.jLabelYUp(bResultadosJornada.getY(), bResultadosJornada.getY()-160, 3, 5, bResultadosJornada);
            animacion.jLabelYUp(bClasificacionGeneral.getY(), bClasificacionGeneral.getY()-160, 3, 5, bClasificacionGeneral);

            animacion.jLabelXLeft(bModificacionEquipos.getX(), bModificacionEquipos.getX()-300, 3, 5, bModificacionEquipos);
            animacion.jLabelXLeft(bModificacionJugadores.getX(), bModificacionJugadores.getX()-300, 3, 5, bModificacionJugadores);
            animacion.jLabelXLeft(bModificacionJefes.getX(), bModificacionJefes.getX()-300, 3, 5, bModificacionJefes);
            animacion.jLabelXLeft(bModificacionUsuarios.getX(), bModificacionUsuarios.getX()-300, 3, 5, bModificacionUsuarios);
        }
        else{
            listaDesplegableModificaciones=true;
            if(listaDesplegableAlta)
            {
                listaDesplegableAlta=false;
                animacion.jLabelXLeft(bAltaEquipos.getX(), bAltaEquipos.getX()-300, 3, 5, bAltaEquipos);
                animacion.jLabelXLeft(bAltaJugadores.getX(), bAltaJugadores.getX()-300, 3, 5, bAltaJugadores);
                animacion.jLabelXLeft(bAltaJefes.getX(), bAltaJefes.getX()-300, 3, 5, bAltaJefes);
                animacion.jLabelXLeft(bAltaUsuarios.getX(), bAltaUsuarios.getX()-300, 3, 5, bAltaUsuarios);

                animacion.jLabelYUp(bBaja.getY(), bBaja.getY()-160, 3, 5, bBaja);
                animacion.jLabelYUp(bModificacion.getY(), bModificacion.getY()-160, 3, 5, bModificacion);

                animacion.jLabelXRight(bModificacionEquipos.getX(), bModificacionEquipos.getX()+300, 3, 5, bModificacionEquipos);
                animacion.jLabelXRight(bModificacionJugadores.getX(), bModificacionJugadores.getX()+300, 3, 5, bModificacionJugadores);
                animacion.jLabelXRight(bModificacionJefes.getX(), bModificacionJefes.getX()+300, 3, 5, bModificacionJefes);
                animacion.jLabelXRight(bModificacionUsuarios.getX(), bModificacionUsuarios.getX()+300, 3, 5, bModificacionUsuarios);
            }
            else if(listaDesplegableBaja)
            {
                listaDesplegableBaja=false;
                animacion.jLabelXLeft(bBajaEquipos.getX(), bBajaEquipos.getX()-300, 3, 5, bBajaEquipos);
                animacion.jLabelXLeft(bBajaJugadores.getX(), bBajaJugadores.getX()-300, 3, 5, bBajaJugadores);
                animacion.jLabelXLeft(bBajaJefes.getX(), bBajaJefes.getX()-300, 3, 5, bBajaJefes);
                animacion.jLabelXLeft(bBajaUsuarios.getX(), bBajaUsuarios.getX()-300, 3, 5, bBajaUsuarios);

                animacion.jLabelYUp(bModificacion.getY(), bModificacion.getY()-160, 3, 5, bModificacion);

                animacion.jLabelXRight(bModificacionEquipos.getX(), bModificacionEquipos.getX()+300, 3, 5, bModificacionEquipos);
                animacion.jLabelXRight(bModificacionJugadores.getX(), bModificacionJugadores.getX()+300, 3, 5, bModificacionJugadores);
                animacion.jLabelXRight(bModificacionJefes.getX(), bModificacionJefes.getX()+300, 3, 5, bModificacionJefes);
                animacion.jLabelXRight(bModificacionUsuarios.getX(), bModificacionUsuarios.getX()+300, 3, 5, bModificacionUsuarios);
            }
            else
            {
                animacion.jLabelYDown(bCalendario.getY(), bCalendario.getY()+160, 3, 5, bCalendario);
                animacion.jLabelYDown(bRealizarEmparejamientos.getY(), bRealizarEmparejamientos.getY()+160, 3, 5, bRealizarEmparejamientos);
                animacion.jLabelYDown(bResultadosJornada.getY(), bResultadosJornada.getY()+160, 3, 5, bResultadosJornada);
                animacion.jLabelYDown(bClasificacionGeneral.getY(), bClasificacionGeneral.getY()+160, 3, 5, bClasificacionGeneral);

                animacion.jLabelXRight(bModificacionEquipos.getX(), bModificacionEquipos.getX()+300, 3, 5, bModificacionEquipos);
                animacion.jLabelXRight(bModificacionJugadores.getX(), bModificacionJugadores.getX()+300, 3, 5, bModificacionJugadores);
                animacion.jLabelXRight(bModificacionJefes.getX(), bModificacionJefes.getX()+300, 3, 5, bModificacionJefes);
                animacion.jLabelXRight(bModificacionUsuarios.getX(), bModificacionUsuarios.getX()+300, 3, 5, bModificacionUsuarios);
            }
        }
    }//GEN-LAST:event_bModificacionMouseClicked

    private void bModificacionEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModificacionEquiposMouseClicked
        Controlador.VentanaModificacionEquipo(this);
    }//GEN-LAST:event_bModificacionEquiposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifEquipo(d).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GIFarriba;
    private javax.swing.JLabel bAceptar;
    private javax.swing.JLabel bAlta;
    private javax.swing.JLabel bAltaEquipos;
    private javax.swing.JLabel bAltaJefes;
    private javax.swing.JLabel bAltaJugadores;
    private javax.swing.JLabel bAltaUsuarios;
    private javax.swing.JLabel bBaja;
    private javax.swing.JLabel bBajaEquipos;
    private javax.swing.JLabel bBajaJefes;
    private javax.swing.JLabel bBajaJugadores;
    private javax.swing.JLabel bBajaUsuarios;
    private javax.swing.JLabel bCalendario;
    private javax.swing.JLabel bCerrar;
    private javax.swing.JLabel bClasificacionGeneral;
    private javax.swing.JLabel bMenu;
    private javax.swing.JLabel bMinimizar;
    private javax.swing.JLabel bModificacion;
    private javax.swing.JLabel bModificacionEquipos;
    private javax.swing.JLabel bModificacionJefes;
    private javax.swing.JLabel bModificacionJugadores;
    private javax.swing.JLabel bModificacionUsuarios;
    private javax.swing.JLabel bModo;
    private javax.swing.JLabel bRealizarEmparejamientos;
    private javax.swing.JLabel bResultadosJornada;
    private javax.swing.JLabel barraDrag;
    private javax.swing.JLabel gifAbajo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField tfIdEquipo;
    private javax.swing.JTextField tfIdJefe;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
